sonar.projectKey=api_crisisview-main
sonar.projectName=api_crisisview-main
sonar.projectVersion=1.0

sonar.sources=routes
sonar.tests=routes
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=node_modules/**,dist/**,public/**
sonar.coverage.exclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
3307